version: "3.9"

networks:
  default:
    external:
      name: medication

services:
  app:
    container_name: medicalfile
    image: medicalfile
    ports:
      - 8086:8086
    networks:
      default:
        aliases:
          - medicalfile
    depends_on:
      - db

  db:
    image: mysql
    container_name: medicalfiledb
    ports:
      - 8089:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=medicalfile
    networks:
      default:
        aliases:
          - medicalfiledb
